spring.application.name=ISW1_ACT_DR_DO_BACK

server.port=8081
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1000Nika944500.
spring.datasource.url=jdbc:mysql://